spring:
  profiles:
    active: dev #활성 프로필 설정
  config:
    cloud:
      openfeign:
        client:
          config:
            default:
              logger-level: FULL
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    map.homepage.domain.member.auth.oauth2.feignClient: DEBUG
naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
  redirect-uri: ${NAVER_REDIRECT_URI}
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
