spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6c34d9a6903231c5a301
            client-secret: 비밀키
            scope: name,email,avatar_url
          google:
            client-id: 54767115914-gcla0mork6h3156h4qcutjerm0mdf4fu.apps.googleusercontent.com
            client-secret: 비밀키
            scope: profile,email
          # 네이버는 spring security가 기본적으로 제공해주지 않기 때문에 github, google과 달리 많은 정보를 적어줘야한다.
          naver:
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization_grant_type: authorization_code
            scope: name,email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
