spring:
  profiles:
    group:
      "local": "local, common"
      "dev": "dev, common"
      "prod": "prod, common"
    active: local #활성 프로필 설정
---
spring:
  config:
    activate:
      on-profile: "local"
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mysql://localhost:3306/map?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 60192234
    driver-class-name: com.mysql.cj.jdbc.Driver
    # JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        format_sql: true      # 쿼리 로그 포맷 (정렬)
        show_sql: true        # 쿼리 로그 출력

---
spring:
  config:
    activate:
      on-profile: "dev"

---
spring:
  config:
    activate:
      on-profile: "prod"

---
spring:
  config:
    activate:
      on-profile: "common"
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: FULL
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    com.onnoff.onnoff.auth.feignClient: DEBUG
